In [ ]:
# create this list [-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0]
results = []
print(results)

In [ ]:
#A list of all the capital letters (and not white space) in 'The Quick Brown Fox Jumped Over The Lazy Dog'
teststring = 'The Quick Brown Fox Jumped Over The Lazy Dog'
results = []
print(results)

In [ ]:
#Find all of the numbers from 1-1000 that are divisible by 7
results = []
print(results)

In [ ]:
#Find all of the numbers from 1-1000 that have a 3 in them
results = []
print(results)

In [ ]:
#Count the number of spaces in a string 
teststring = 'Find all of the words in a string that are less than 4 letters'
#print teststring.count(' ')   # normally I'd just do this, but for the practice....
results = []
print(len(results))

In [ ]:
#Remove all of the vowels in a string [make a list of the non-vowels]
teststring = 'Find all of the words in a string that are less than 4 letters'
results = []
print(results)

In [ ]:
#Find all of the words in a string that are less than 4 letters
teststring = 'Find all of the words in a string that are less than 4 letters'
results = []
print(results)

## CHALLENGE!

In [ ]:
#Use a dictionary comprehension to count the length of each word in a sentence.
sentence = 'Use a dictionary comprehension to count the length of each word in a sentence'
results = []
print(results)

### Example

In [ ]:
#Use a nested list comprehension to find all of the numbers from 1-100 that 
#are divisible by any single digit besides 1 (2-9)
# comprehension testing truth for divisibilty: [True for divisor in range(2,10) if number % divisor == 0]
results = [number for number in range(1,101) if True in [True for divisor in range(2,10) if number % divisor == 0]]
print(results)

In [ ]:
# Find all prime numbers in 1-100
# answer: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 
# 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97.
results = []

In [ ]:
#For all the numbers 1-100, use a nested list/dictionary comprehension to 
#find the highest single digit any of the numbers is divisible by.
# List comprehension for providing a list of all of the numbers a number is divisible by: divisor_list:
#       [divisor for divisor in range(1,1001) if number % divisor == 0]
results = {}
print(results)

## Lambda function and Map, Filter, Reduce

### ``Map`` applies a function to all the items in an input_list.


In [ ]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, items))

### ``Filter`` creates a list of elements for which a function returns true.

In [ ]:
number_list = range(-5, 5)
less_than_zero = list(filter(lambda x: x<0, number_list))
print(less_than_zero)

In [ ]:
my_list = ["geeks", "geeg", "keek", "practice", "aa"] 
# use anonymous function to filter palindromes. 
result = list(filter(lambda x: (x == x[::-1]), my_list))  
print(result)  

In [ ]:
# Python Program to find numbers divisible  
# by 13 from a list using anonymous function 
my_list = [12, 65, 54, 39, 102, 339, 221, 50, 70, ] 
result = list(filter(lambda x: (x % 13 == 0), my_list))  
print(result)  

### ``Reduce`` is a really useful function for performing some computation on a list and returning the result. It applies a __rolling__ computation to sequential pairs of values in a list. For example, if you wanted to compute the product of a list of integers.

In [ ]:
from functools import reduce
product = reduce((lambda x, y: x * y), [1, 2, 3, 4])
print(product)

# Array broadcasting

## Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [110]:
M = np.ones((2, 3))
a = np.arange(3)

In [111]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [112]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [113]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [114]:
M = np.ones((3, 2))
a = np.arange(3)
a + M

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [115]:
a[:, np.newaxis].shape

(3, 1)

In [116]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [117]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])