In [103]:
# create this list [-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0]
results = [num for num in range(-10,1)]
print([-num for num in range(0,11)[::-1]])
print(results)

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]


In [105]:
#A list of all the capital letters (and not white space) in 'The Quick Brown Fox Jumped Over The Lazy Dog'
teststring = 'The Quick Brown Fox Jumped Over The Lazy Dog'
results = [letter for letter in teststring if letter.islower()]
print(results)

['h', 'e', 'u', 'i', 'c', 'k', 'r', 'o', 'w', 'n', 'o', 'x', 'u', 'm', 'p', 'e', 'd', 'v', 'e', 'r', 'h', 'e', 'a', 'z', 'y', 'o', 'g']


In [106]:
#Find all of the numbers from 1-1000 that are divisible by 7
results = [num for num in range(1001) if num % 7 == 0]
print(results)

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875, 882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973, 980, 987, 994]


In [107]:
num = 342436
list(str(num))

['3', '4', '2', '4', '3', '6']

In [108]:
#Find all of the numbers from 1-1000 that have a 3 in them
results = [num for num in range(1001) if '3' in list(str(num))]
print(results)

[3, 13, 23, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 53, 63, 73, 83, 93, 103, 113, 123, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 143, 153, 163, 173, 183, 193, 203, 213, 223, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 243, 253, 263, 273, 283, 293, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 403, 413, 423, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 443, 453, 463, 473, 483, 493, 503, 513, 523, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 543, 553, 563, 573, 583, 593, 603, 613, 623, 630, 631, 632, 633, 634, 635,

In [111]:
#Count the number of spaces in a string 
teststring = 'Find all of the words in a string that are less than 4 letters'
#print teststring.count(' ')   # normally I'd just do this, but for the practice....
results = [character for character in teststring if character == ' ']
print(len(results))

13


In [ ]:
#Remove all of the vowels in a string [make a list of the non-vowels]
teststring = 'Find all of the words in a string that are less than 4 letters'
vowels = ['a','e','i','o','u',' ']
results = [letter for letter in teststring if letter.lower() not in vowels]
print(results)

In [ ]:
teststring = 'Find all of the words in a string that are less than 4 letters'
results = [word for word in teststring.split() if len(word) < 4]
print(results)

## CHALLENGE!

In [112]:
#Use a dictionary comprehension to count the length of each word in a sentence.
sentence = 'Use a dictionary comprehension to count the length of each word in a sentence'
results = {word:len(word) for word in sentence.split()}
print(results)

{'Use': 3, 'a': 1, 'dictionary': 10, 'comprehension': 13, 'to': 2, 'count': 5, 'the': 3, 'length': 6, 'of': 2, 'each': 4, 'word': 4, 'in': 2, 'sentence': 8}


### Example

In [116]:
number = 24

In [117]:
[True for divisor in range(2,10) if number % divisor == 0]

[True, True, True, True, True]

In [118]:
#Use a nested list comprehension to find all of the numbers from 1-100 that 
#are divisible by any single digit besides 1 (2-9)
# comprehension testing truth for divisibilty: [True for divisor in range(2,10) if number % divisor == 0]
results = [number for number in range(1,101) if True in [True for divisor in range(2,10) if number % divisor == 0]]
print(results)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 38, 39, 40, 42, 44, 45, 46, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 60, 62, 63, 64, 65, 66, 68, 69, 70, 72, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 98, 99, 100]


In [125]:
number = 121

In [126]:
[True for divisor in range(2,10) if number % divisor == 0 and number != divisor]

[]

In [127]:
# Find all prime numbers in 1-100
# answer: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 
# 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97.
results = [number for number in range(2,101) if True not in [True for divisor in range(2,10) if number % divisor == 0 and number != divisor]]
print(results)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [ ]:
#For all the numbers 1-10, use a nested list/dictionary comprehension to 
#find the highest single digit any of the numbers is divisible by.
# List comprehension for providing a list of all of the numbers a number is divisible by: divisor_list:
#       [divisor for divisor in range(1,1001) if number % divisor == 0]
results = {number:max([divisor for divisor in range(1,10) if number % divisor == 0]) for number in range(1,101)}
print(results)

## Lambda function and Map, Filter, Reduce

### ``Map`` applies a function to all the items in an input_list.


In [128]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, items))
squared

[1, 4, 9, 16, 25]

### ``Filter`` creates a list of elements for which a function returns true.

In [130]:
number_list = range(-5, 5)
less_than_zero = list(filter(lambda x: x<0, number_list))
print(less_than_zero)

[-5, -4, -3, -2, -1]


In [131]:
my_list = ["geeks", "geeg", "keek", "practice", "aa"] 
# use anonymous function to filter palindromes. 
result = list(filter(lambda x: (x == x[::-1]), my_list))  
print(result)  

['geeg', 'keek', 'aa']


In [133]:
# Python Program to find numbers divisible  
# by 13 from a list using anonymous function 
my_list = [12, 65, 54, 39, 102, 339, 221, 50, 70, 235] 
result = list(filter(lambda x: (x % 13 == 0), my_list))  
print(result)  

[65, 39, 221]


### ``Reduce`` is a really useful function for performing some computation on a list and returning the result. It applies a __rolling__ computation to sequential pairs of values in a list. For example, if you wanted to compute the product of a list of integers.

In [134]:
from functools import reduce

product = reduce((lambda x, y: x * y), [1, 2, 3, 4, 11, 34, 12345, 22])
print(product)

2437791840


# Array broadcasting

## Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [135]:
M = np.ones((2, 3))
a = np.arange(3)

In [136]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [137]:
a

array([0, 1, 2])

In [138]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [139]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [142]:
print(np.tile(a, (1,3)))
print(np.tile(b, (3,1)))

[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [150]:
c = np.tile(b, (3,2))
c

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [153]:
np.sum(c, axis=0)

array([0, 3, 6, 0, 3, 6])

In [102]:
import numpy as np; np.tile(a, (1,3))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
a + b

In [143]:
M = np.ones((3, 2))
a = np.arange(3)
a + M

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [144]:
a

array([0, 1, 2])

In [145]:
a[:, np.newaxis].shape

(3, 1)

In [146]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [147]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

## [Advanced numpy exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)